/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AppointmentOut {
  address?: (string | null);
  appointment_date: string;
  completed_date?: (string | null);
  email?: (string | null);
  id?: (number | null);
  name: string;
  phone?: (string | null);
  service_type?: string;
  status?: string;
  work_done?: (string | null);
}
