/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvoiceIn {
  appointment_id: number;
  discount?: (number | string);
  subtotal?: (number | string);
  tax?: (number | string);
  total?: (number | string);
  total_parts?: (number | string);
  total_service?: (number | string);
  warranty_extension?: boolean;
}
