/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvoiceOut {
  appointment: number;
  discount?: string;
  id?: (number | null);
  subtotal?: string;
  tax?: string;
  total?: string;
  total_parts?: string;
  total_service?: string;
  warranty_extension?: boolean;
}
