/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PartInstanceOut } from '../models/part-instance-out';
export interface PagedPartInstanceOut {
  count: number;
  items: Array<PartInstanceOut>;
}
