/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AppointmentOut } from '../models/appointment-out';
export interface PagedAppointmentOut {
  count: number;
  items: Array<AppointmentOut>;
}
