/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PartInstanceOut {
  appointment: number;
  id?: (number | null);
  part: number;
  serial_number?: (string | null);
}
