/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PartOut {
  brand: string;
  id?: (number | null);
  model_number: string;
  name: string;
  warranty?: (string | null);
}
