# Generated by Django 6.1.2 on 2026-10-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', '예약'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('CANCELLED', '취소')], default='SCHEDULED', max_length=30),
        ),
    ]
