/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PartOut } from '../../models/part-out';

export interface GetPart$Params {
  part_id: number;
}

export function getPart(http: HttpClient, rootUrl: string, params: GetPart$Params, context?: HttpContext): Observable<StrictHttpResponse<PartOut>> {
  const rb = new RequestBuilder(rootUrl, getPart.PATH, 'get');
  if (params) {
    rb.path('part_id', params.part_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PartOut>;
    })
  );
}

getPart.PATH = '/api/inventory/{part_id}';
