/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PartInstanceOut } from '../../models/part-instance-out';

export interface GetPartInstance$Params {
  instance_id: number;
}

export function getPartInstance(http: HttpClient, rootUrl: string, params: GetPartInstance$Params, context?: HttpContext): Observable<StrictHttpResponse<PartInstanceOut>> {
  const rb = new RequestBuilder(rootUrl, getPartInstance.PATH, 'get');
  if (params) {
    rb.path('instance_id', params.instance_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PartInstanceOut>;
    })
  );
}

getPartInstance.PATH = '/api/inventory/instances/{instance_id}';
