/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedPartInstanceOut } from '../../models/paged-part-instance-out';

export interface ListPartInstances$Params {
  limit?: number;
  offset?: number;
}

export function listPartInstances(http: HttpClient, rootUrl: string, params?: ListPartInstances$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedPartInstanceOut>> {
  const rb = new RequestBuilder(rootUrl, listPartInstances.PATH, 'get');
  if (params) {
    rb.query('limit', params.limit, {});
    rb.query('offset', params.offset, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedPartInstanceOut>;
    })
  );
}

listPartInstances.PATH = '/api/inventory/instances';
