/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PartIn } from '../../models/part-in';
import { PartOut } from '../../models/part-out';

export interface UpdatePart$Params {
  part_id: number;
      body: PartIn
}

export function updatePart(http: HttpClient, rootUrl: string, params: UpdatePart$Params, context?: HttpContext): Observable<StrictHttpResponse<PartOut>> {
  const rb = new RequestBuilder(rootUrl, updatePart.PATH, 'put');
  if (params) {
    rb.path('part_id', params.part_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PartOut>;
    })
  );
}

updatePart.PATH = '/api/inventory/{part_id}';
