/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PartInstanceIn } from '../../models/part-instance-in';
import { PartInstanceOut } from '../../models/part-instance-out';

export interface UpdatePartInstance$Params {
  instance_id: number;
      body: PartInstanceIn
}

export function updatePartInstance(http: HttpClient, rootUrl: string, params: UpdatePartInstance$Params, context?: HttpContext): Observable<StrictHttpResponse<PartInstanceOut>> {
  const rb = new RequestBuilder(rootUrl, updatePartInstance.PATH, 'put');
  if (params) {
    rb.path('instance_id', params.instance_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PartInstanceOut>;
    })
  );
}

updatePartInstance.PATH = '/api/inventory/instances/{instance_id}';
