/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ListAppointments$Params as ListAppointments$Params } from './fn/appointments/list-appointments';
export { listAppointments as listAppointments } from './fn/appointments/list-appointments';
export type { CreateAppointment$Params as CreateAppointment$Params } from './fn/appointments/create-appointment';
export { createAppointment as createAppointment } from './fn/appointments/create-appointment';
export type { GetAppointment$Params as GetAppointment$Params } from './fn/appointments/get-appointment';
export { getAppointment as getAppointment } from './fn/appointments/get-appointment';
export type { UpdateAppointment$Params as UpdateAppointment$Params } from './fn/appointments/update-appointment';
export { updateAppointment as updateAppointment } from './fn/appointments/update-appointment';
export type { ListAppointmentInvoices$Params as ListAppointmentInvoices$Params } from './fn/appointments/list-appointment-invoices';
export { listAppointmentInvoices as listAppointmentInvoices } from './fn/appointments/list-appointment-invoices';
export type { CreateInvoice$Params as CreateInvoice$Params } from './fn/appointments/create-invoice';
export { createInvoice as createInvoice } from './fn/appointments/create-invoice';
export type { GetInvoice$Params as GetInvoice$Params } from './fn/appointments/get-invoice';
export { getInvoice as getInvoice } from './fn/appointments/get-invoice';
export type { UpdateInvoice$Params as UpdateInvoice$Params } from './fn/appointments/update-invoice';
export { updateInvoice as updateInvoice } from './fn/appointments/update-invoice';
export type { ListAppointmentParts$Params as ListAppointmentParts$Params } from './fn/appointments/list-appointment-parts';
export { listAppointmentParts as listAppointmentParts } from './fn/appointments/list-appointment-parts';
export type { ListParts$Params as ListParts$Params } from './fn/inventory/list-parts';
export { listParts as listParts } from './fn/inventory/list-parts';
export type { CreatePart$Params as CreatePart$Params } from './fn/inventory/create-part';
export { createPart as createPart } from './fn/inventory/create-part';
export type { GetPart$Params as GetPart$Params } from './fn/inventory/get-part';
export { getPart as getPart } from './fn/inventory/get-part';
export type { UpdatePart$Params as UpdatePart$Params } from './fn/inventory/update-part';
export { updatePart as updatePart } from './fn/inventory/update-part';
export type { GetPartInstance$Params as GetPartInstance$Params } from './fn/inventory/get-part-instance';
export { getPartInstance as getPartInstance } from './fn/inventory/get-part-instance';
export type { UpdatePartInstance$Params as UpdatePartInstance$Params } from './fn/inventory/update-part-instance';
export { updatePartInstance as updatePartInstance } from './fn/inventory/update-part-instance';
export type { ListPartInstances$Params as ListPartInstances$Params } from './fn/inventory/list-part-instances';
export { listPartInstances as listPartInstances } from './fn/inventory/list-part-instances';
export type { CreatePartInstance$Params as CreatePartInstance$Params } from './fn/inventory/create-part-instance';
export { createPartInstance as createPartInstance } from './fn/inventory/create-part-instance';
