/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AppointmentIn } from './models/appointment-in';
export type { AppointmentOut } from './models/appointment-out';
export type { InvoiceIn } from './models/invoice-in';
export type { InvoiceOut } from './models/invoice-out';
export type { PagedAppointmentOut } from './models/paged-appointment-out';
export type { PagedPartInstanceOut } from './models/paged-part-instance-out';
export type { PagedPartOut } from './models/paged-part-out';
export type { PartIn } from './models/part-in';
export type { PartInstanceIn } from './models/part-instance-in';
export type { PartInstanceOut } from './models/part-instance-out';
export type { PartOut } from './models/part-out';
