/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AppointmentsService } from './services/appointments.service';
export { InventoryService } from './services/inventory.service';
