/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AppointmentOut } from '../models/appointment-out';
import { createAppointment } from '../fn/appointments/create-appointment';
import { CreateAppointment$Params } from '../fn/appointments/create-appointment';
import { createInvoice } from '../fn/appointments/create-invoice';
import { CreateInvoice$Params } from '../fn/appointments/create-invoice';
import { getAppointment } from '../fn/appointments/get-appointment';
import { GetAppointment$Params } from '../fn/appointments/get-appointment';
import { getInvoice } from '../fn/appointments/get-invoice';
import { GetInvoice$Params } from '../fn/appointments/get-invoice';
import { InvoiceOut } from '../models/invoice-out';
import { listAppointmentInvoices } from '../fn/appointments/list-appointment-invoices';
import { ListAppointmentInvoices$Params } from '../fn/appointments/list-appointment-invoices';
import { listAppointmentParts } from '../fn/appointments/list-appointment-parts';
import { ListAppointmentParts$Params } from '../fn/appointments/list-appointment-parts';
import { listAppointments } from '../fn/appointments/list-appointments';
import { ListAppointments$Params } from '../fn/appointments/list-appointments';
import { PagedAppointmentOut } from '../models/paged-appointment-out';
import { PartInstanceOut } from '../models/part-instance-out';
import { updateAppointment } from '../fn/appointments/update-appointment';
import { UpdateAppointment$Params } from '../fn/appointments/update-appointment';
import { updateInvoice } from '../fn/appointments/update-invoice';
import { UpdateInvoice$Params } from '../fn/appointments/update-invoice';

@Injectable({ providedIn: 'root' })
export class AppointmentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listAppointments()` */
  static readonly ListAppointmentsPath = '/api/appointments/';

  /**
   * List Appointments.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listAppointments()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAppointments$Response(params?: ListAppointments$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedAppointmentOut>> {
    const obs = listAppointments(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List Appointments.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listAppointments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAppointments(params?: ListAppointments$Params, context?: HttpContext): Observable<PagedAppointmentOut> {
    const resp = this.listAppointments$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PagedAppointmentOut>): PagedAppointmentOut => r.body)
    );
  }

  /** Path part for operation `createAppointment()` */
  static readonly CreateAppointmentPath = '/api/appointments/';

  /**
   * Create Appointment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createAppointment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAppointment$Response(params: CreateAppointment$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentOut>> {
    const obs = createAppointment(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Create Appointment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createAppointment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAppointment(params: CreateAppointment$Params, context?: HttpContext): Observable<AppointmentOut> {
    const resp = this.createAppointment$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<AppointmentOut>): AppointmentOut => r.body)
    );
  }

  /** Path part for operation `getAppointment()` */
  static readonly GetAppointmentPath = '/api/appointments/{appointment_id}';

  /**
   * Get Appointment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAppointment()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAppointment$Response(params: GetAppointment$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentOut>> {
    const obs = getAppointment(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get Appointment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAppointment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAppointment(params: GetAppointment$Params, context?: HttpContext): Observable<AppointmentOut> {
    const resp = this.getAppointment$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<AppointmentOut>): AppointmentOut => r.body)
    );
  }

  /** Path part for operation `updateAppointment()` */
  static readonly UpdateAppointmentPath = '/api/appointments/{appointment_id}';

  /**
   * Update Appointment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateAppointment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAppointment$Response(params: UpdateAppointment$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentOut>> {
    const obs = updateAppointment(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Update Appointment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateAppointment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAppointment(params: UpdateAppointment$Params, context?: HttpContext): Observable<AppointmentOut> {
    const resp = this.updateAppointment$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<AppointmentOut>): AppointmentOut => r.body)
    );
  }

  /** Path part for operation `listAppointmentInvoices()` */
  static readonly ListAppointmentInvoicesPath = '/api/appointments/{appointment_id}/invoices';

  /**
   * List Appointment Invoices.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listAppointmentInvoices()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAppointmentInvoices$Response(params: ListAppointmentInvoices$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InvoiceOut>>> {
    const obs = listAppointmentInvoices(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List Appointment Invoices.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listAppointmentInvoices$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAppointmentInvoices(params: ListAppointmentInvoices$Params, context?: HttpContext): Observable<Array<InvoiceOut>> {
    const resp = this.listAppointmentInvoices$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<InvoiceOut>>): Array<InvoiceOut> => r.body)
    );
  }

  /** Path part for operation `createInvoice()` */
  static readonly CreateInvoicePath = '/api/appointments/invoices';

  /**
   * Create Invoice.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createInvoice()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createInvoice$Response(params: CreateInvoice$Params, context?: HttpContext): Observable<StrictHttpResponse<InvoiceOut>> {
    const obs = createInvoice(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Create Invoice.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createInvoice$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createInvoice(params: CreateInvoice$Params, context?: HttpContext): Observable<InvoiceOut> {
    const resp = this.createInvoice$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<InvoiceOut>): InvoiceOut => r.body)
    );
  }

  /** Path part for operation `getInvoice()` */
  static readonly GetInvoicePath = '/api/appointments/invoices/{invoice_id}';

  /**
   * Get Invoice.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getInvoice()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInvoice$Response(params: GetInvoice$Params, context?: HttpContext): Observable<StrictHttpResponse<InvoiceOut>> {
    const obs = getInvoice(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get Invoice.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getInvoice$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInvoice(params: GetInvoice$Params, context?: HttpContext): Observable<InvoiceOut> {
    const resp = this.getInvoice$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<InvoiceOut>): InvoiceOut => r.body)
    );
  }

  /** Path part for operation `updateInvoice()` */
  static readonly UpdateInvoicePath = '/api/appointments/invoices/{invoice_id}';

  /**
   * Update Invoice.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateInvoice()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateInvoice$Response(params: UpdateInvoice$Params, context?: HttpContext): Observable<StrictHttpResponse<InvoiceOut>> {
    const obs = updateInvoice(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Update Invoice.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateInvoice$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateInvoice(params: UpdateInvoice$Params, context?: HttpContext): Observable<InvoiceOut> {
    const resp = this.updateInvoice$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<InvoiceOut>): InvoiceOut => r.body)
    );
  }

  /** Path part for operation `listAppointmentParts()` */
  static readonly ListAppointmentPartsPath = '/api/appointments/{appointment_id}/part_instances';

  /**
   * List Appointment Parts.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listAppointmentParts()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAppointmentParts$Response(params: ListAppointmentParts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PartInstanceOut>>> {
    const obs = listAppointmentParts(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List Appointment Parts.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listAppointmentParts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAppointmentParts(params: ListAppointmentParts$Params, context?: HttpContext): Observable<Array<PartInstanceOut>> {
    const resp = this.listAppointmentParts$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<PartInstanceOut>>): Array<PartInstanceOut> => r.body)
    );
  }

}
