/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createPart } from '../fn/inventory/create-part';
import { CreatePart$Params } from '../fn/inventory/create-part';
import { createPartInstance } from '../fn/inventory/create-part-instance';
import { CreatePartInstance$Params } from '../fn/inventory/create-part-instance';
import { getPart } from '../fn/inventory/get-part';
import { GetPart$Params } from '../fn/inventory/get-part';
import { getPartInstance } from '../fn/inventory/get-part-instance';
import { GetPartInstance$Params } from '../fn/inventory/get-part-instance';
import { listPartInstances } from '../fn/inventory/list-part-instances';
import { ListPartInstances$Params } from '../fn/inventory/list-part-instances';
import { listParts } from '../fn/inventory/list-parts';
import { ListParts$Params } from '../fn/inventory/list-parts';
import { PagedPartInstanceOut } from '../models/paged-part-instance-out';
import { PagedPartOut } from '../models/paged-part-out';
import { PartInstanceOut } from '../models/part-instance-out';
import { PartOut } from '../models/part-out';
import { updatePart } from '../fn/inventory/update-part';
import { UpdatePart$Params } from '../fn/inventory/update-part';
import { updatePartInstance } from '../fn/inventory/update-part-instance';
import { UpdatePartInstance$Params } from '../fn/inventory/update-part-instance';

@Injectable({ providedIn: 'root' })
export class InventoryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listParts()` */
  static readonly ListPartsPath = '/api/inventory/';

  /**
   * List Parts.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listParts()` instead.
   *
   * This method doesn't expect any request body.
   */
  listParts$Response(params?: ListParts$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedPartOut>> {
    const obs = listParts(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List Parts.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listParts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listParts(params?: ListParts$Params, context?: HttpContext): Observable<PagedPartOut> {
    const resp = this.listParts$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PagedPartOut>): PagedPartOut => r.body)
    );
  }

  /** Path part for operation `createPart()` */
  static readonly CreatePartPath = '/api/inventory/';

  /**
   * Create Part.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createPart()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPart$Response(params: CreatePart$Params, context?: HttpContext): Observable<StrictHttpResponse<PartOut>> {
    const obs = createPart(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Create Part.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createPart$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPart(params: CreatePart$Params, context?: HttpContext): Observable<PartOut> {
    const resp = this.createPart$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PartOut>): PartOut => r.body)
    );
  }

  /** Path part for operation `getPart()` */
  static readonly GetPartPath = '/api/inventory/{part_id}';

  /**
   * Get Part.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPart()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPart$Response(params: GetPart$Params, context?: HttpContext): Observable<StrictHttpResponse<PartOut>> {
    const obs = getPart(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get Part.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPart$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPart(params: GetPart$Params, context?: HttpContext): Observable<PartOut> {
    const resp = this.getPart$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PartOut>): PartOut => r.body)
    );
  }

  /** Path part for operation `updatePart()` */
  static readonly UpdatePartPath = '/api/inventory/{part_id}';

  /**
   * Update Part.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updatePart()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePart$Response(params: UpdatePart$Params, context?: HttpContext): Observable<StrictHttpResponse<PartOut>> {
    const obs = updatePart(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Update Part.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updatePart$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePart(params: UpdatePart$Params, context?: HttpContext): Observable<PartOut> {
    const resp = this.updatePart$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PartOut>): PartOut => r.body)
    );
  }

  /** Path part for operation `getPartInstance()` */
  static readonly GetPartInstancePath = '/api/inventory/instances/{instance_id}';

  /**
   * Get Part Instance.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPartInstance()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPartInstance$Response(params: GetPartInstance$Params, context?: HttpContext): Observable<StrictHttpResponse<PartInstanceOut>> {
    const obs = getPartInstance(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get Part Instance.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPartInstance$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPartInstance(params: GetPartInstance$Params, context?: HttpContext): Observable<PartInstanceOut> {
    const resp = this.getPartInstance$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PartInstanceOut>): PartInstanceOut => r.body)
    );
  }

  /** Path part for operation `updatePartInstance()` */
  static readonly UpdatePartInstancePath = '/api/inventory/instances/{instance_id}';

  /**
   * Update Part Instance.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updatePartInstance()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePartInstance$Response(params: UpdatePartInstance$Params, context?: HttpContext): Observable<StrictHttpResponse<PartInstanceOut>> {
    const obs = updatePartInstance(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Update Part Instance.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updatePartInstance$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePartInstance(params: UpdatePartInstance$Params, context?: HttpContext): Observable<PartInstanceOut> {
    const resp = this.updatePartInstance$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PartInstanceOut>): PartInstanceOut => r.body)
    );
  }

  /** Path part for operation `listPartInstances()` */
  static readonly ListPartInstancesPath = '/api/inventory/instances';

  /**
   * List Part Instances.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listPartInstances()` instead.
   *
   * This method doesn't expect any request body.
   */
  listPartInstances$Response(params?: ListPartInstances$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedPartInstanceOut>> {
    const obs = listPartInstances(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List Part Instances.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listPartInstances$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listPartInstances(params?: ListPartInstances$Params, context?: HttpContext): Observable<PagedPartInstanceOut> {
    const resp = this.listPartInstances$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PagedPartInstanceOut>): PagedPartInstanceOut => r.body)
    );
  }

  /** Path part for operation `createPartInstance()` */
  static readonly CreatePartInstancePath = '/api/inventory/instances';

  /**
   * Create Part Instance.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createPartInstance()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPartInstance$Response(params: CreatePartInstance$Params, context?: HttpContext): Observable<StrictHttpResponse<PartInstanceOut>> {
    const obs = createPartInstance(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Create Part Instance.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createPartInstance$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPartInstance(params: CreatePartInstance$Params, context?: HttpContext): Observable<PartInstanceOut> {
    const resp = this.createPartInstance$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PartInstanceOut>): PartInstanceOut => r.body)
    );
  }

}
