# Generated by Django 6.1.2 on 2026-10-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='warranty',
            field=models.TextField(blank=True),
        ),
    ]
