/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppointmentOut } from '../../models/appointment-out';

export interface GetAppointment$Params {
  appointment_id: number;
}

export function getAppointment(http: HttpClient, rootUrl: string, params: GetAppointment$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentOut>> {
  const rb = new RequestBuilder(rootUrl, getAppointment.PATH, 'get');
  if (params) {
    rb.path('appointment_id', params.appointment_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppointmentOut>;
    })
  );
}

getAppointment.PATH = '/api/appointments/{appointment_id}';
