/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvoiceOut } from '../../models/invoice-out';

export interface GetInvoice$Params {
  invoice_id: number;
}

export function getInvoice(http: HttpClient, rootUrl: string, params: GetInvoice$Params, context?: HttpContext): Observable<StrictHttpResponse<InvoiceOut>> {
  const rb = new RequestBuilder(rootUrl, getInvoice.PATH, 'get');
  if (params) {
    rb.path('invoice_id', params.invoice_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvoiceOut>;
    })
  );
}

getInvoice.PATH = '/api/appointments/invoices/{invoice_id}';
