/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvoiceOut } from '../../models/invoice-out';

export interface ListAppointmentInvoices$Params {
  appointment_id: number;
}

export function listAppointmentInvoices(http: HttpClient, rootUrl: string, params: ListAppointmentInvoices$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InvoiceOut>>> {
  const rb = new RequestBuilder(rootUrl, listAppointmentInvoices.PATH, 'get');
  if (params) {
    rb.path('appointment_id', params.appointment_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<InvoiceOut>>;
    })
  );
}

listAppointmentInvoices.PATH = '/api/appointments/{appointment_id}/invoices';
