/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PartInstanceOut } from '../../models/part-instance-out';

export interface ListAppointmentParts$Params {
  appointment_id: number;
}

export function listAppointmentParts(http: HttpClient, rootUrl: string, params: ListAppointmentParts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PartInstanceOut>>> {
  const rb = new RequestBuilder(rootUrl, listAppointmentParts.PATH, 'get');
  if (params) {
    rb.path('appointment_id', params.appointment_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PartInstanceOut>>;
    })
  );
}

listAppointmentParts.PATH = '/api/appointments/{appointment_id}/part_instances';
