/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedAppointmentOut } from '../../models/paged-appointment-out';

export interface ListAppointments$Params {
  limit?: number;
  offset?: number;
}

export function listAppointments(http: HttpClient, rootUrl: string, params?: ListAppointments$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedAppointmentOut>> {
  const rb = new RequestBuilder(rootUrl, listAppointments.PATH, 'get');
  if (params) {
    rb.query('limit', params.limit, {});
    rb.query('offset', params.offset, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedAppointmentOut>;
    })
  );
}

listAppointments.PATH = '/api/appointments/';
