/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppointmentIn } from '../../models/appointment-in';
import { AppointmentOut } from '../../models/appointment-out';

export interface UpdateAppointment$Params {
  appointment_id: number;
      body: AppointmentIn
}

export function updateAppointment(http: HttpClient, rootUrl: string, params: UpdateAppointment$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentOut>> {
  const rb = new RequestBuilder(rootUrl, updateAppointment.PATH, 'put');
  if (params) {
    rb.path('appointment_id', params.appointment_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppointmentOut>;
    })
  );
}

updateAppointment.PATH = '/api/appointments/{appointment_id}';
