/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvoiceIn } from '../../models/invoice-in';
import { InvoiceOut } from '../../models/invoice-out';

export interface UpdateInvoice$Params {
  invoice_id: number;
      body: InvoiceIn
}

export function updateInvoice(http: HttpClient, rootUrl: string, params: UpdateInvoice$Params, context?: HttpContext): Observable<StrictHttpResponse<InvoiceOut>> {
  const rb = new RequestBuilder(rootUrl, updateInvoice.PATH, 'put');
  if (params) {
    rb.path('invoice_id', params.invoice_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvoiceOut>;
    })
  );
}

updateInvoice.PATH = '/api/appointments/invoices/{invoice_id}';
